"""removes asset analytics table

Revision ID: 2f92ac60d9a5
Revises: ba3fe7f9cb75
Create Date: 2025-10-16 20:33:44.359860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f92ac60d9a5'
down_revision = 'ba3fe7f9cb75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_asset_performance_asset_date', table_name='asset_performance_metrics')
    op.drop_index('idx_asset_performance_asset_id', table_name='asset_performance_metrics')
    op.drop_index('idx_asset_performance_date', table_name='asset_performance_metrics')
    op.drop_index('ix_asset_performance_metrics_id', table_name='asset_performance_metrics')
    op.drop_table('asset_performance_metrics')
    op.drop_index('idx_asset_correlation_asset1', table_name='asset_correlations')
    op.drop_index('idx_asset_correlation_asset2', table_name='asset_correlations')
    op.drop_index('idx_asset_correlation_date', table_name='asset_correlations')
    op.drop_index('ix_asset_correlations_id', table_name='asset_correlations')
    op.drop_table('asset_correlations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_correlations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('correlation_1m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('correlation_3m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('correlation_6m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('correlation_1y', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('correlation_3y', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('rolling_correlation_20d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('rolling_correlation_60d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('p_value', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('is_significant', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset1_id'], ['assets.id'], name='asset_correlations_asset1_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset2_id'], ['assets.id'], name='asset_correlations_asset2_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='asset_correlations_pkey'),
    sa.UniqueConstraint('asset1_id', 'asset2_id', 'calculation_date', name='uq_asset_correlation')
    )
    op.create_index('ix_asset_correlations_id', 'asset_correlations', ['id'], unique=False)
    op.create_index('idx_asset_correlation_date', 'asset_correlations', ['calculation_date'], unique=False)
    op.create_index('idx_asset_correlation_asset2', 'asset_correlations', ['asset2_id'], unique=False)
    op.create_index('idx_asset_correlation_asset1', 'asset_correlations', ['asset1_id'], unique=False)
    op.create_table('asset_performance_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=False),
    sa.Column('price_change', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('price_change_percent', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('sma_20', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('sma_50', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('sma_200', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('ema_12', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('ema_26', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('rsi', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd_signal', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd_histogram', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('stochastic_k', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('stochastic_d', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('bollinger_upper', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('bollinger_middle', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('bollinger_lower', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('atr', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('volume_sma', sa.NUMERIC(precision=20, scale=0), autoincrement=False, nullable=True),
    sa.Column('volume_ratio', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('obv', sa.NUMERIC(precision=20, scale=0), autoincrement=False, nullable=True),
    sa.Column('volatility_20d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('volatility_60d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('volatility_252d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('beta', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('sharpe_ratio', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('total_return_1m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('total_return_3m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('total_return_6m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('total_return_1y', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('total_return_3y', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('total_return_5y', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='asset_performance_metrics_asset_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='asset_performance_metrics_pkey'),
    sa.UniqueConstraint('asset_id', 'calculation_date', name='uq_asset_performance_date')
    )
    op.create_index('ix_asset_performance_metrics_id', 'asset_performance_metrics', ['id'], unique=False)
    op.create_index('idx_asset_performance_date', 'asset_performance_metrics', ['calculation_date'], unique=False)
    op.create_index('idx_asset_performance_asset_id', 'asset_performance_metrics', ['asset_id'], unique=False)
    op.create_index('idx_asset_performance_asset_date', 'asset_performance_metrics', ['asset_id', 'calculation_date'], unique=False)
    # ### end Alembic commands ###
