"""removes portfolio risk metrics table

Revision ID: ba3fe7f9cb75
Revises: f9322944f1cd
Create Date: 2025-10-15 21:05:34.350897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba3fe7f9cb75'
down_revision = 'f9322944f1cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_portfolio_risk_date', table_name='portfolio_risk_metrics')
    op.drop_index('idx_portfolio_risk_portfolio_date', table_name='portfolio_risk_metrics')
    op.drop_index('idx_portfolio_risk_portfolio_id', table_name='portfolio_risk_metrics')
    op.drop_index('ix_portfolio_risk_metrics_id', table_name='portfolio_risk_metrics')
    op.drop_table('portfolio_risk_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_risk_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('portfolio_volatility', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('portfolio_beta', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('portfolio_alpha', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('sharpe_ratio', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('sortino_ratio', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('treynor_ratio', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('calmar_ratio', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('max_drawdown_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_drawdown', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('var_95_1d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('var_99_1d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('var_95_1m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('var_99_1m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('cvar_95_1d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('cvar_99_1d', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('risk_level', postgresql.ENUM('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='risklevel'), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('concentration_risk', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('effective_number_of_assets', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('diversification_ratio', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('average_correlation', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('max_correlation', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='portfolio_risk_metrics_portfolio_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='portfolio_risk_metrics_pkey'),
    sa.UniqueConstraint('portfolio_id', 'calculation_date', name='uq_portfolio_risk_date')
    )
    op.create_index('ix_portfolio_risk_metrics_id', 'portfolio_risk_metrics', ['id'], unique=False)
    op.create_index('idx_portfolio_risk_portfolio_id', 'portfolio_risk_metrics', ['portfolio_id'], unique=False)
    op.create_index('idx_portfolio_risk_portfolio_date', 'portfolio_risk_metrics', ['portfolio_id', 'calculation_date'], unique=False)
    op.create_index('idx_portfolio_risk_date', 'portfolio_risk_metrics', ['calculation_date'], unique=False)
    # ### end Alembic commands ###
