"""removes asset analytics table

Revision ID: e3e5f6f4d0a1
Revises: 2f92ac60d9a5
Create Date: 2025-10-16 20:36:42.353857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e5f6f4d0a1'
down_revision = '2f92ac60d9a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
