services:
  streamlit:
    build: ./python/streamlit
    ports:
      - 8501:8501
    env_file:
      - js/.env.docker
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
  app:
    build: ./js
    volumes:
      - ./js/src:/app/src
    ports:
      - 3000:3000
    env_file:
      - js/.env.docker
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
  api:
    build: 
      context: ./python/api
      dockerfile: Dockerfile
    env_file:
      - ./python/api/.env.docker
    ports:
      - "${API_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # Development: Mount source code for live reload (exclude cache)
      - ./python/api/app:/app/app:delegated
      - ./python/api/schemas:/app/schemas:delegated
      - ./python/api/utils:/app/utils:delegated
      - ./python/api/api:/app/api:delegated
      - ./python/api/alembic:/app/alembic:delegated
      - ./python/api/services:/app/services:delegated
      - ./python/api/start_api.py:/app/start_api.py:delegated
      - ./python/api/start_api.sh:/app/start_api.sh:delegated
      - ./python/api/requirements.txt:/app/requirements.txt:delegated
    networks:
      - portfolio_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  data-service:
    build: 
      context: ./python/api
      dockerfile: Dockerfile
    command: ["python", "start_data_service.py"]
    env_file:
      - ./python/api/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # Mount source code for live reload
      - ./python/api/app:/app/app:delegated
      - ./python/api/schemas:/app/schemas:delegated
      - ./python/api/services:/app/services:delegated
      - ./python/api/start_data_service.py:/app/start_data_service.py:delegated
      - ./python/api/requirements.txt:/app/requirements.txt:delegated
    networks:
      - portfolio_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import psycopg2; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15
    env_file:
      - ./python/api/.env.docker
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    env_file:
      - ./python/api/.env.docker
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  redis_data:

networks:
  portfolio_network:
    driver: bridge
