version: "3.8"

services:
  streamlit:
    build: ./python/streamlit
    ports:
      - 8501:8501
  app:
    build: ./js
    volumes:
      - ./js/src:/app/src
    ports:
      - 3000:3000
  api:
    build: ./python/api
    ports:
      - 8080:8080
