version: "3.8"

services:
  streamlit:
    build: ./python/streamlit
    ports:
      - 8501:8501
  app:
    build: ./js
    volumes:
      - ./js/src:/app/src
    ports:
      - 3000:3000
  api:
    env_file:
      - .env
    build: ./python/api
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16.1-alpine
    volumes:
      - data:/var/lib/postgresql/data/
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "5432:5432"

volumes:
  data: