version: "3.8"

services:
  streamlit:
    build: ./python/streamlit
    ports:
      - 8501:8501
  app:
    build: ./js
    volumes:
      - ./js/src:/app/src
    ports:
      - 3000:3000
  api:
    build: ./python/api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:16.1-alpine
    volumes:
      - portfolio_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=portfolio
    ports: 
      - "5432:5432"

volumes:
  portfolio_data: