services:
  streamlit:
    build: ./python/streamlit
    ports:
      - 8501:8501
    networks:
      - portfolio_network
      
  app:
    build: ./js
    volumes:
      - ./js/src:/app/src
    ports:
      - 3000:3000
    networks:
      - portfolio_network
      
  api:
    build: 
      context: ./python/api
      dockerfile: Dockerfile
      target: development
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-portfolio}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - DEBUG=${DEBUG:-true}
      - PYTHONPATH=/app
      - PORT=8000
      - HOST=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # Development: Mount source code for live reload
      - ./python/api:/app:delegated
      # Exclude virtual environment and cache
      - /app/.venv
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.coverage
    networks:
      - portfolio_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
  postgres:
    image: postgres:16.2-alpine
    volumes:
      - portfolio_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-portfolio}
    ports: 
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - portfolio_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-portfolio}"]
      interval: 10s
      timeout: 10s
      retries: 5
      
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - portfolio_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  portfolio_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  portfolio_data:
    driver: local
  redis_data:
    driver: local