version: "3.8"

services:
  web:
    build: ./python/streamlit
    ports:
      - 8501:8501
  app:
    container_name: app-dev
    image: app-dev
    build: ./js
    volumes:
      - ./js/src:/app/src
    ports:
      - 3000:3000
